### ISSUE TITLE
Flat and Sharp at the same time

### ISSUE THREAD

**Issue by fmmagalhaes** [jsrmath/sharp11#5]
Hey there!

First of all, congratulations for the awesome work you did here.

Second, I've been reading chord.js. I see ninths are either aug, m or M (lines 103-116). This way you either have #9 or b9, not both.

So, in the sharp11-client if you write C11b9#9, it'll be assumed to be a C11#9. However, if you add the note C#, the output you get is indeed C11b9#9.

Shouldn't that be solved?

**Comment by jsrmath** [comment]
Hi Francisco,

Thanks for reaching out!  The b9#9 is an interesting case, because it's the only time that you can have an interval appear twice in a chord with two different alterations (unclear whether this is even technically "allowed" but I'm sure you can find it in jazz somewhere).  I'm not too concerned about the inconsistency, because the relationship between chord names and groups of notes can never be one-to-one, since you can have different names for the same chord and also have the same chord represented as different groups of notes.  The real question is is it worth having the chord name parser recognize b9#9.  It would require a special case, which is not out of the question, but I'm not sure if it's pressing.  I'm actually in the middle of somewhat of a sharp11 overhaul at the moment, so I'll leave this issue open and possibly get to it as part of this overhaul.  Thank you for bringing this to my attention.

Best,
Julian

**Comment by fmmagalhaes** [comment]
Indeed, the inconsistency is not an issue in this case. However, when trying to identify one chord, sometimes you don't get the expected output. Although it may just be a matter of opinion, when you use C E G# A# D F# A, you get C13b5#5 instead of Caug13#11 (or C+13#11). I'm not sure that's an issue but I'd rather get Caug13#11. This happens because b5=#11 and aug implies #5.

There are a couple of other cases like this. However, ofc you can't just please everyone when it comes to chord names. But I'd still like to hear your opinion on this.

**Comment by jsrmath** [comment]
I agree that you should get Caug13#11 in that example.  Currently I choose `#11` when there is a perfect fifth present and `b5` when there isn't.  I should change the case to perfect fifth or raised fifth.
