### ISSUE TITLE
Invalid intervals

### ISSUE THREAD

**Issue by dmmz** [jsrmath/sharp11#9]
Why shouldn't it be possible to calculate interval between for instance C# and Gb and get a P4 (perfect 4th)? what I do for the moment is that I convert Gb to F#, but I guess it should be possible.

**Comment by jsrmath** [comment]
As a rule, Sharp11 treats spelling literally.  That means, for example, that the interval between C and Eb is a m3 but the interval between C and D# is an aug2.  This prevents inconsistencies across Sharp11 functions, allows the user to be precise in terms of what accidentals they want, and guarantees that answers will always be technically correct.  The problem with C# and Gb is there is no technical name for that interval.  It must be a fifth of some sort, because C and G are a fifth apart, but there is no name for a doubly diminished fifth.  Can you provide a little more context about where this calculation is occurring, and maybe I can suggest a solution?

**Comment by dmmz** [comment]
What you say makes sense.  But what I want to do is to calculate intervals in a melody or a chord sequence. I don't care about spelling: for me C - D# is exactly the same as C - Eb.  So far, my solution is: if both pitches have an accidental (# or b) and they are different, I change the second pitch using 'toggleAccidental' method

**Comment by jsrmath** [comment]
You could also pick either sharps or flats and convert all your notes to the appropriate accidental with [`.withAccidental`](https://github.com/jsrmath/sharp11/blob/master/docs/note.md#-withaccidental-withaccidentalacc).  The benefit here is you can just invoke the function on every note blindly and it will ignore it if there are no accidentals.

**Comment by dmmz** [comment]
Ok! thanks
